# Generated by Django 3.1.1 on 2020-10-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=3)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=10)),
                ('problem', models.CharField(max_length=22)),
                ('place', models.CharField(max_length=52)),
            ],
        ),
    ]
